apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telex
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AugustHottie/telex-deployment.git
    targetRevision: HEAD
    path: ./Telex-Manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: telex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
