apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    name: minio
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  MINIO_ROOT_USER: ZWtlaWtlbm5hCg==
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9090
        envFrom:
        - secretRef:
            name: minio-secret
        volumeMounts:
        - mountPath: /data
          name: localvolume 
      volumes:
      - name: localvolume
        hostPath:
          path: /mnt/disk1/data 
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    app: minio
  ports:
  - protocol: TCP
    port: 9004
    targetPort: 9090
